<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- Versión del prototipo: esquema 1.x.y-beta+z ligado a ahp.v1 [AGENT.md] -->
  <PropertyGroup>
    <FusionVersion>2.3.0</FusionVersion>
    <FusionStage>estudio-nativo-web</FusionStage>
  </PropertyGroup>
</Project>
