<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net35;net48</TargetFrameworks>
    <RootNamespace>lumina.bridge</RootNamespace>
    <AssemblyName>Lumina.Bridge</AssemblyName>
    <Summary>Puente P/Invoke hacia el núcleo nativo LuminaCore (ABI C plana, UTF-8).</Summary>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Lumina.Core/Lumina.Core.csproj" />
  </ItemGroup>

</Project>
