<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net35;net48</TargetFrameworks>
    <RootNamespace>fusion.poc</RootNamespace>
    <AssemblyName>FusionHP.PocFacade</AssemblyName>
    <Summary>Fachada COM-visible (sin registro) consumida por el PoC nativo CLR-Hosting.</Summary>
  </PropertyGroup>

</Project>
